spring:
  profiles:
    active:development
---
#配置文件名称
spring:
  profiles:development
#freemarker前缀
spring:  
  freemarker:
    prefix:
#JDBC配置 
spring:
  datasource:
    #type指定使用druid连接池
    type=com.alibaba.druid.pool.DruidDataSource
    url:jdbc:mysql://localhost:3306/springboot
    username:root
    password:root
    driver-class-name:com.mysql.jdbc.Driver

#连接池配置
spring:
  datasource:
    druid:
      initial-size:2
      max-active:10
#      min-idle:
#      max-wait:
#      pool-prepared-statements:
#      max-pool-prepared-statement-per-connection-size:
#      validation-query:
#      validation-query-timeout:
#      test-on-borrow:
#      test-on-return:
#      test-while-idle:
#      time-between-eviction-runs-millis:
#      min-evictable-idle-time-millis:
#      max-evictable-idle-time-millis:
spring:
  datasource:
    druid:
         filter:
         # 配置StatFilter 
           stat:
             db-type:h2
             log-slow-sql:true
             slow-sql-millis:2000
         # 配置WallFilter 
           wall:
             enabled:true
             db-type:h2
             delete-allow:false
             drop-table-allow:false
      

   
    
my:
  server:
    address:127.0.0.1
  
  
  
---
spring:
  profiles:production

    
  
  